spring:
  application:
    name: taskTracker

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

tasktracker:
  max-tasks: 50
  default-page-size: 10